- alias: "State Triggered: Announce whenever gate is opened."
  description: ""
  trigger:
    - entity_id: binary_sensor.gate_sensor_contact
      platform: state
      to: "on"
  condition: []
  action:
    - service: script.announce
      data: '{"my_message":"Gate opened"}'
  mode: single
