- platform: template
  switches:
    pihole_switch:
      friendly_name: PiholeSwitch
      value_template: "{{ is_state('sensor.pihole_status', 'enabled') }}"
      turn_on:
        - service: pihole.enable
      turn_off:
        - service: pihole.disable
          data:
            duration: "00.05"

- platform: rest
  resource: http://127.0.0.1:8126/container/logitech-media-server
  name: Logitech Media Server
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: template
  switches:
    white_noise_onoff:
      value_template: '{{ states("input_boolean.white_noise") }}'
      friendly_name: "White Noise"
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.white_noise
        - service: script.white_noise

      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.white_noise
        - service: media_player.media_stop
          data:
            entity_id: media_player.bedroom_pair
        - service: media_player.media_stop
          data:
            entity_id: media_player.bedroom_pair_LMS

- platform: template
  switches:
    white_noise_kelly_onoff:
      value_template: '{{ states("input_boolean.white_noise_kelly") }}'
      friendly_name: "White Noise"
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.white_noise_kelly
        - service: script.white_noise_kelly

      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.white_noise_kelly
        - service: media_player.media_stop
          data:
            entity_id: media_player.kelly_speaker
