- platform: template
  switches:
    white_noise_onoff:
      value_template: '{{ states("input_boolean.white_noise") }}'
      friendly_name: "White Noise"
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.white_noise
        - service: script.white_noise

      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.white_noise
        - service: media_player.media_stop
          data:
            entity_id: media_player.bedroom_pair
        - service: media_player.media_stop
          data:
            entity_id: media_player.bedroom_pair_LMS

- platform: template
  switches:
    white_noise_kelly_onoff:
      value_template: '{{ states("input_boolean.white_noise_kelly") }}'
      friendly_name: "White Noise"
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.white_noise_kelly
        - service: script.white_noise_kelly

      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.white_noise_kelly
        - service: media_player.media_stop
          data:
            entity_id: media_player.kelly_speaker
