---
button_card_templates: !include_dir_merge_named "../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"
decluttering_templates: !include_dir_merge_named "../custom_ui/decluttering_templates"

title: Home
swipe_nav:
  wrap: true
  animate: fade
  prevent_default: true
  swipe_amount: 15
  skip_tabs: 2,3,4,5,6,7,8,9
views:
  ## BEGIN TEST HOME ###
  - title: Test Home
    path: test-home
    icon: mdi:picture-in-picture-bottom-right
    badges: []
    cards:
      - type: vertical-stack
        cards:
          ## Chips Row ##
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
              - type: custom:button-card
                template: chip_temperature
                tap_action:
                  action: navigate
                  navigation_path: /ui-lovelace-minimalist/weather
                variables:
                  ulm_chip_temperature_inside: sensor.average_indoor_temperature
                  ulm_chip_temperature_outside: sensor.temperature
                  ulm_chip_temperature_weather: weather.kamloops
              - type: custom:button-card
                entity: alarm_control_panel.panel
                template: chip_alarm
                tap_action:
                  action: navigate
                  navigation_path: /ui-lovelace-minimalist/security
              - type: custom:button-card
                template: chip_presence_detection
                variables:
                  ulm_chip_presence_counter_residents: sensor.presence_detection
              - type: "custom:button-card"
                template: chip_navigate
                label: ""
                variables:
                  ulm_chip_navigate_path: /ui-lovelace-minimalist/heating
                  ulm_chip_navigate_icon: mdi:thermometer
              - type: "custom:button-card"
                color_type: blank-card
          ## Persons Card ##
          - type: horizontal-stack
            cards:
              - template: person_card_new
                type: custom:decluttering-card
                variables:
                  - entity: person.colton
                  - name: Colton
                  - show_name: false
                  - show_state: false
                  - battery: device_tracker.life360_colton
                  - wifi: sensor.colton_s_samsung_wifi_connection
                  - entity_picture: /local/colton.jpg
                  - show_entity_picture: true
                  - tap_action:
                      action: more-info
                      haptic: light
              - template: person_card_new
                type: custom:decluttering-card
                variables:
                  - entity: person.miranda
                  - name: Miranda
                  - show_name: false
                  - show_state: false
                  - battery: device_tracker.life360_miranda
                  - wifi: sensor.miranda_wifi_connection
                  - entity_picture: /local/miranda.jpg
                  - show_entity_picture: true
                  - tap_action:
                      action: more-info
                      haptic: light
          ## Buttons ##
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: "custom:button-card"
                    template:
                      - card_input_boolean
                      - green_on
                    entity: input_boolean.override_home
                    name: Override
                  - type: "custom:button-card"
                    template:
                      - card_input_boolean
                      - green_on
                    entity: switch.white_noise_onoff
                    name: Sleep
              - type: vertical-stack
                cards:
                  - type: "custom:button-card"
                    template:
                      - card_input_boolean
                      - green_on
                    entity: switch.party_switch
                    name: Party
                  - type: "custom:button-card"
                    template:
                      - card_input_boolean
                      - green_on
                    entity: input_boolean.vacation_mode
                    name: Vacation Mode
          # title card
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                template: card_title
                name: Heating
              - type: "custom:button-card"
                color_type: blank-card

          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: custom_card_coltondick_thermostat
                entity: climate.living_room_thermostats
                variables:
                  ulm_card_thermostat_enable_collapse: false
                  ulm_card_thermostat_enable_controls: true
                  ulm_card_thermostat_enable_background_color: true
                  ulm_card_thermostat_enable_hvac_modes: false
                  ulm_card_thermostat_enable_popup: false
      - type: vertical-stack
        cards:
          # title card
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                template: card_title
                name: Rooms
              - type: "custom:button-card"
                color_type: blank-card
          - type: horizontal-stack
            cards:
              ## Entry Way ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Entry Way
                entity: light.entryway_ceiling
                icon: hue:room-hallway
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: false
                  label_use_brightness: false
                  room_temperature: sensor.average_indoor_temperature
                  entity_1:
                    entity_id: lock.front_door
                    templates:
                      - custom_coltondick_lock_on
                      - custom_coltondick_lock_off
                    tap_action:
                      action: toggle
                  entity_2:
                    entity_id: switch.patio_lights
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_3:
                    entity_id: light.laundry_room_ceiling
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                ## Dining Room ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Dining Room
                entity: light.dining_room_ceiling
                icon: hue:room-dining
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: true
                  label_use_brightness: false
                  room_temperature: sensor.dining_room_temperature
                  entity_1:
                    entity_id: light.hue_light_strip
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_2:
                    entity_id: switch.scentsy
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
          - type: horizontal-stack
            cards:
              ## Kitchen ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Kitchen
                entity: light.kitchen_ceiling
                icon: hue:room-kitchen
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: false
                  label_use_brightness: false
                  entity_1:
                    entity_id: light.kitchen_stove
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_2:
                    entity_id: switch.kitchen_leds
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
              ## Living Room ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Living Room
                entity: light.living_room_ceiling
                icon: hue:room-living
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: true
                  label_use_brightness: false
                  room_temperature: sensor.living_room_temperature
                  entity_1:
                    entity_id: remote.tv
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_2:
                    entity_id: switch.side_table_lamp
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_3:
                    entity_id: switch.cage
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_4:
                    entity_id: light.tv_leds
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
          - type: horizontal-stack
            cards:
              ## Master ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Master Bedroom
                entity: group.bedroom
                icon: hue:room-bedroom
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: true
                  label_use_brightness: false
                  room_temperature: sensor.bedroom_thermostat_temperature
                  entity_1:
                    entity_id: remote.bedroom
                    templates:
                      - green_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_2:
                    entity_id: switch.vanity
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
                  entity_3:
                    entity_id: switch.bedroom_sidetable_lamp
                    templates:
                      - yellow_on
                      - grey_off
                    tap_action:
                      action: toggle
              ## Office ##
              - type: "custom:button-card"
                template:
                  - custom_card_coltondick_room
                  - grey_off
                  - blue_on
                name: Office
                entity: light.office_ceiling_group
                icon: hue:room-office
                templates:
                  - yellow_on
                tap_action:
                  action: toggle
                variables:
                  label_use_temperature: true
                  label_use_brightness: false
                  room_temperature: sensor.office_temperature
                  entity_1:
                    entity_id: media_player.spotify_colt_dick
                    templates:
                      - custom_coltondick_media_on
                      - custom_coltondick_media_off
                    tap_action:
                      action: call-service
                      service: script.play_pause_spotify
                      service_data:
                        entity_id: media_player.spotify_colt_dick
