# Automatically turn on|off the guinea pig cage.
- alias: "Turn Cage Lights On at 7 AM"
  trigger:
    platform: time
    at: "07:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.cage

- alias: "Turn Cage Lights Off at 10 PM"
  trigger:
    platform: time
    at: "22:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.cage
