- alias: "Denon Set Volume"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_number.denon_volume
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.denon_avr_s720w
        volume_level: >
          {{states('input_number.denon_volume') | int / 100}}

- alias: "Denon Update Volume Slider"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: sensor.denon_volume
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: media_player.denon_avr_s720w # receiver must be on to set the volume, without this would throw error on startup
    state: "on"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.denon_volume
        value: >-
          {% set value = int(trigger.to_state.state) %}
            {{ value }}
